// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoursesAPI.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string Crs_Name { get; set; }

    [StringLength(50)]
    public string Crs_Desc { get; set; }

    public int? Duration { get; set; }

    public int Dept_Id { get; set; }

    [ForeignKey("Dept_Id")]
    [InverseProperty("Courses")]
    public virtual Department Dept { get; set; }
}