// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoursesAPI.Models;

[Table("Department")]
public partial class Department
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Manager { get; set; }

    [StringLength(50)]
    public string Location { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}